# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: DAST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: (0) Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: (1) Enter Vuply venv
      run: |
        python -m venv .
        . ./bin/activate
    - name: (2) Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: (3) Initialize DB
      run: |
        ./bad/db_init.py
    - name: (4) Run dev webserver
      run: | 
        cd bad && flask --app vulpy run
